<?php
/**
 * This class has been auto-generated by PHP-DI.
 */
class CompiledContainer extends DI\CompiledContainer{
    const METHOD_MAPPING = array (
  'dbConfig' => 'get1',
  'Http\\Controllers\\HomeController' => 'get2',
);

    protected function get1()
    {
        return NULL;
    }

    protected function get2()
    {
        $object = new Http\Controllers\HomeController();
        return $object;
    }

}
